CREATE TABLE EPL_Predictor.`Training_Set_0.0.1` (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	Home_Team_DEF TINYINT NOT NULL,
	Home_Team_MID TINYINT NOT NULL,
	Home_Team_ATT TINYINT NOT NULL,
	Away_Team_DEF TINYINT NOT NULL,
	Away_Team_MID varchar(100) NOT NULL,
	Away_Team_ATT TINYINT NOT NULL,
	`Result` TINYINT NOT NULL,
	CONSTRAINT PK PRIMARY KEY (id)
)
ENGINE=InnoDB
DEFAULT CHARSET=latin1
COLLATE=latin1_swedish_ci;
